# Generated by Django 5.1.1 on 2024-09-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='date',
        ),
    ]
